### ISSUE TITLE
start up

### ISSUE THREAD

**Issue by EstebanExplorer** [caiotaniguchi/super-zoom-it#1]
Hello friend greetings from colombia
I am working on my degree project, on super resolution and investigating my limit with its repository, I was wondering if I could orientate myself on its implementation since I find it very interesting.

Beforehand thank you very much

Excuse me for my english I use the google translate

**Comment by caiotaniguchi** [comment]
Hi, @calidoso. I'm sorry to say that I won't be able to help you much, as I dropped this project long ago. This was actually an attempt at porting a Matlab script. Unfortunately, it's not working and I never figured out why. You could fork this repository to use it as a starting point or you could start from scratch.

Anyway, I'll leave the article I used as reference here: http://ieeexplore.ieee.org/document/6947980/

Contacting the author of the above might be helpful.

**Comment by EstebanExplorer** [comment]
Thanks friend for the prompt reply,
No way, I'll take a look at the code to see if it works for me.

regards
